version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5446:5432"
    volumes:
    - ../db/postgresql-scripts/1-create-tables.sql:/docker-entrypoint-initdb.d/1-create-tables.sql
    - db-data:/var/lib/postgresql/data
  web-service:
    build:
      context: ../src
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      DatabaseConnectionString: User ID=postgres;Password=password;Host=postgres;Port=5432;Database=postgres
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
    - ./service-data:/app/files

volumes:
  db-data:
